Add individual download tracker for every video
mellowagain/pomu pull request #19
Opened 2023-02-05 13:22 UTC by MatyasEngelen

2023-02-05 21:02 UTC, emily33901 requested changes
nits around logging, newlines at ends of files and component structure

2023-02-05 21:02 UTC, emily33901 commented on migrations/000004_dowloads_tracker_up.sql
> +commit;
newline at end of file please

2023-02-05 21:02 UTC, emily33901 commented on migrations/000004_dowloads_tracker_down.sql
> +commit;
new line at end of file please

2023-02-05 21:02 UTC, emily33901 commented on src/lib/VideoEntry.svelte
> +                <div style="overflow: hidden; text-align: right; float: right; display: flex;">
if youre embedding the svg here, could you make this its own component

2023-02-05 21:02 UTC, emily33901 commented on download.go
> +			tx, err_db := app.db.Begin()
```suggestion
			tx, err := app.db.Begin()
```

2023-02-05 21:02 UTC, emily33901 commented on download.go
> +				log.Println("cannot start transaction (downloads) ", err_db)
please make use of the new loguru format

```suggestion
				log.WithFields(log.Fields{"error": err}).Error("cannot start transaction (downloads)")
```

2023-02-05 21:02 UTC, emily33901 commented on download.go
> +				log.Println("Download counter error: ", err)
```suggestion
				log.WithFields(log.Fields{"error": err}).Error("Download counter error")
```

2023-02-05 21:02 UTC, emily33901 commented on download.go
> +			//I believe a non vital function like this should just log the error instead of returning http
```suggestion
			// I believe a non vital function like this should just log the error instead of returning http
```

2023-02-05 21:02 UTC, emily33901 commented on download.go
> +				log.Println("Download counter error: ", err)
```suggestion
				log.WithFields(log.Fields{"error": err}).Error("Download counter error")
```

2023-02-05 21:02 UTC, emily33901 commented on download.go
> +				log.Println("Download counter error (Commit): ", err)
```suggestion
				log.WithFields(log.Fields{"error": err}).Error("Download counter error (Commit)")
```

2023-02-05 21:04 UTC, mellowagain commented on src/lib/VideoEntry.svelte
> +                <div style="overflow: hidden; text-align: right; float: right; display: flex;">
its actually just a icon so you can just do `<CloudDownload />`

2023-02-05 21:07 UTC, mellowagain commented
please also add the new `VideoInfo` attribute to the openapi file

2023-06-09 00:12 UTC, mellowagain commented
replaced by https://github.com/mellowagain/pomu/pull/25

2023-06-09 00:12 UTC, closed without merging